#!/bin/bash
#
# A very simple BASH script to take an input video and generate sprite JPG image
# from video thumbs in equal sequence of time periods.
#
#

######################################################################################
#
# Copyright (c) 2018, Nuevolab.com
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided for everyone without restrictions

function print_usage(){

cat << EOM
Video Sprite Generator
Version 1
Copyright (C) 2018 Nuevolab.com

Usage: spritevideo -i [inputfile] -w [width] -h [height] -o [outputdir] -p [outputfile]
	-i	Input video file
	-o	Output directory
	-p	Output jpg file
EOM
exit
}


if hash ffmpeg 2> /dev/null
then
  # FFMpeg exists
  echo "ffmpeg command found.... continuing"
else
  # FFMPeg doesn't exist, uh-oh!
  echo "Error: FFmpeg doesn't appear to exist in your PATH. Please addresss and try again"
  exit 1
fi

command -v convert >/dev/null 2>&1 || { echo >&2 "Imagemagick not installed.  Aborting."; exit 1; }

INPUTFILE=""
OUTPUT_DIRECTORY=""
OUTPUT_FILENAME=""
SPRITE_WIDTH=160
SPRITE_HEIGHT=90


while getopts ":i:o:p:w:h:" optname
  do
    case "$optname" in
      "i")
        INPUTFILE=$OPTARG
        ;;
      "o")
        OUTPUT_DIRECTORY=$OPTARG
        ;;
      "p")
        OUTPUTFILE=$OPTARG
        ;;
      "e")
        OUTPUTFILE2=$OPTARG
        ;;
      "w")
        SPRITE_WIDTH=$OPTARG
	;;
      "h")
	SPRITE_HEIGHT=$OPTARG
	;;
    esac
  done



if [ ! -f "$INPUTFILE" ]
then 
	INPUTFILE=""
	echo "Input video file does not exist. Exiting ..."
	exit 1
fi
if [ ! -d "$OUTPUT_DIRECTORY" ]
then 
	OUTPUT_DIRECTORY="" 
	echo "Output directory does not exist. Exiting ..."
	exit 1
fi

if [ "$OUTPUTFILE" == "" ]
then
	echo "Output file not defined. Exiting ..."
	exit 1
fi



# get video duration, v1
fulltime=`ffmpeg -i "$INPUTFILE" 2>&1 | grep 'Duration' | cut -d ' ' -f 4 | sed s/,//`;

seconds=0;
hour=`echo $fulltime | cut -d ':' -f 1`;
minute=`echo $fulltime | cut -d ':' -f 2`;
second=`echo $fulltime | cut -d ':' -f 3 | cut -d '.' -f 1`;
duration=`expr 3600 \* $hour + 60 \* $minute + $second`;

if [[ "$duration" -gt 0 ]]; 
then

	


	frequency=$((($duration / 100) + ($duration % 100 > 0)))
	#frequency=$(echo $duration / 150 | bc -l)


	echo "Video Duration: $duration seconds";
	echo "Frequency: $frequency";
	
	#min=1

	#if [ 1 -eq "$(echo "${frequency} < ${min}" | bc)" ]
	#then
		#frequency=${min}
	#fi



	if [ $frequency -lt 1 ] 
	then 
	frequency=1;
	fi


	i=0;
	j=0;


	TMPDIR=$(date +%s.%N)
	mkdir "$OUTPUT_DIRECTORY/$TMPDIR"
	chmod 777 "$OUTPUT_DIRECTORY/$TMPDIR"


	
	total=0
	
	while [ $i -lt $duration ]
	do
		if [ $j -lt 10 ] ; 
		then

		thumb="$OUTPUT_DIRECTORY/$TMPDIR/0$j.jpg"
		else

		thumb="$OUTPUT_DIRECTORY/$TMPDIR/09$j.jpg"
		echo $thumb
		fi
		ffmpeg -loglevel panic -ss "$i" -i "$INPUTFILE" -vframes 1 -f image2 -s "$SPRITE_WIDTH"x"$SPRITE_HEIGHT" "$thumb"
		
		i=`expr $i + $frequency`
		j=`expr $j + 1`
		total=`expr $total + 1`
		

	done

	if [ -f $OUTPUTFILE ] ; then
		rm -f $OUTPUTFILE
	fi

	ffmpeg -pattern_type glob -i "$OUTPUT_DIRECTORY/$TMPDIR/*.jpg" -filter_complex tile=1x$total -y "$OUTPUTFILE"


	rm -rf "$OUTPUT_DIRECTORY/$TMPDIR"

	if [ -f "$OUTPUTFILE" ] 
	then
	echo ""
	echo "SUCCESS!"
	echo ""
	fi
else
	echo "Video duration = 0. Exiting..."
	exit 1

fi




